/*
*********************************************************************************************************
*   											uC/OS-II
*   											实时内核
*
*   					 (c) Copyright 1992-1998, Jean J. Labrosse, Plantation, FL
*   											版权所有
*                                       STC89C52RC Specific code
*   										
*
* 文件名 : INCLUDES.H
* 作者   : Jean J. Labrosse
* Modify	   : Hantech
* Date  	   : 2015.06.11
*********************************************************************************************************
*/

#include	<stdarg.h>
#include	<stdio.h>
#include	<string.h>
#include	<ctype.h>
#include	<stdlib.h>
#include	<setjmp.h>

#include	"os_cpu.h"
#include	"os_cfg.h"
#include	"\UCOSII\ucos_ii.h"


#include	<reg52.H>
#include	<intrins.h>

