SET C51INC=D:\SProgram Files\Keil5\C51\Inc;D:\SProgram Files\Keil5\C51\Inc\STC
SET C51LIB=D:\SProgram Files\Keil5\C51\Lib
SET CPU_TYPE=STC90C52RC
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"D:\SProgram Files\Keil5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\SProgram Files\Keil5\C51\BIN\C51.EXE" @".\Objects\main.__i"
"D:\SProgram Files\Keil5\C51\BIN\BL51.EXE" @".\Objects\test.lnp"
"D:\SProgram Files\Keil5\C51\BIN\OH51.EXE" ".\Objects\test" 
